# Generated by Django 2.2 on 2019-04-03 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('gln', models.IntegerField()),
                ('address', models.TextField(max_length=150)),
                ('tax_card', models.CharField(max_length=15)),
                ('commercial_record', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=30)),
                ('inst_type', models.CharField(choices=[('1', 'Factory'), ('2', 'Toll'), ('3', 'Under-Reg'), ('4', 'Importer')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('active_ingredient', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('gtin', models.IntegerField()),
                ('quantity', models.CharField(max_length=60)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_business.Institution')),
            ],
        ),
    ]
