# Generated by Django 2.2 on 2019-04-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_business', '0002_auto_20190405_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_ingredient', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='active_ingredient',
        ),
        migrations.AlterField(
            model_name='fcompany',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='commercial_record',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='gln',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='tax_card',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='active_ing',
            field=models.ManyToManyField(to='all_business.ActiveIng'),
        ),
    ]
