# Generated by Django 2.2 on 2019-04-09 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_business', '0003_auto_20190405_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcompany',
            name='app_type',
        ),
        migrations.RemoveField(
            model_name='fcompany',
            name='e2b',
        ),
        migrations.RemoveField(
            model_name='fcompany',
            name='icsr_status',
        ),
        migrations.RemoveField(
            model_name='fcompany',
            name='medra_license_file',
        ),
        migrations.RemoveField(
            model_name='fcompany',
            name='medra_license_no',
        ),
        migrations.RemoveField(
            model_name='fcompany',
            name='medra_status',
        ),
        migrations.RemoveField(
            model_name='fcompany',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='pvsystem',
            name='system_type_id',
        ),
        migrations.AddField(
            model_name='pvsystem',
            name='app_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='pvsystem',
            name='e2b',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='pvsystem',
            name='icsr_status',
            field=models.CharField(blank=True, choices=[('E', 'Exist'), ('O', 'Exists Outside'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pvsystem',
            name='medra_license_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='pvsystem',
            name='medra_license_no',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='pvsystem',
            name='medra_status',
            field=models.CharField(blank=True, choices=[('E', 'Exist'), ('O', 'Exists Outside'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pvsystem',
            name='system_type',
            field=models.CharField(blank=True, choices=[('SS', 'PSSF'), ('ML', 'PSMF For Local'), ('MA', 'PSMF For Agent')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='pvsystem',
            name='team_members',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='pvsystem',
            name='thirdparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_business.ThirdParty'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='sdea_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='fcompany',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='fcompany',
            name='contract_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='fcompany',
            name='pv_system_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_business.PvSystem'),
        ),
        migrations.AlterField(
            model_name='fcompany',
            name='qppv_email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='fcompany',
            name='qppv_mobile',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='fcompany',
            name='qppv_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='fcompany',
            name='reg_no',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='fcompany',
            name='relations',
            field=models.CharField(blank=True, choices=[('A', 'Agent'), ('B', 'Branch')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fcompany',
            name='sdea_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='inst_type',
            field=models.CharField(blank=True, choices=[('F', 'Factory'), ('T', 'Toll'), ('U', 'Under-Reg'), ('I', 'Importer')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gtin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_business.Institution'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='company_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='f_company_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='gm_email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='gm_mobile',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pvsystem',
            name='gm_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='certificates_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='certificates_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='company_email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='company_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='contract_date',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='contract_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='educations_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='educations_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='email_formal',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='email_personal',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='job_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='middle_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='mobile_formal',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='mobile_personal',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='nationalid',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='nationalid_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='social_insurance_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='social_insurance_no',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppv',
            name='tafweed',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='certificates_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='certificates_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='company_email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='company_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='contract_date',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='contract_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='educations_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='educations_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='email_formal',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='email_personal',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='job_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='middle_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='mobile_formal',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='mobile_personal',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='nationalid',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='nationalid_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='social_insurance_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='social_insurance_no',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qppvdeputy',
            name='tafweed',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='commercial_record',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='commercial_record_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='tax_card',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='tax_card_file',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
