# Generated by Django 2.2 on 2019-04-10 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_business', '0005_institution_pvsystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='address',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='gln',
        ),
    ]
